### ISSUE TITLE
Recipe App Kanban Board

### ISSUE THREAD

**Issue by rega1237** [rbanos-mv/rails-recipe-app#26]
[Kanban Board](https://github.com/rbanos-mv/rails-recipe-app/projects/1)

Teams members : 2 members

Team member 1 : @rbanos-mv 
Team member 2 : @rega1237

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
